name: ci/gh-actions/copyright
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 1 *'
jobs:
  send-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Send pull-request
        run: |
          LATEST_TAG=$(git describe --tags --always --abbrev=0)
          REPOSITORY="some-user/some-repository"
          FOLDER="bin/$REPOSITORY"
          BRANCH_NAME="chore-update-scripts-to-$LATEST_TAG"

          # Clone the remote repository 
          git clone https://github.com/selsta/monero.git

          # Setup the committers identity.
          git config user.email "copyCat@cat.com"
          git config user.name "copyCat"

          # Create a new feature branch for the changes.
          git checkout -b external_bump_copyright

          # Run da script.
          year=$(date +%Y)
          echo "YEAR=$(echo $year)" >> $GITHUB_ENV
          find . -print0 | while IFS= read -r -d '' file
          do
              if [[ -d $file ]] || [[ $file == *".git"* ]]; then
                  continue
              fi
              line=$(grep .*Copyright.*Monero.* $file || true)
              if [[ -z $line ]]; then
                  continue
              fi
              fromTo=$(grep -o "[0-9]\{4\}-[0-9]\{4\}" <<< $line || true)
              if [[ ! -z $fromTo ]]; then
                  # string contains "FROM-TO"
                  # we need to replace TO with current year
                  to=$(awk '{split($0, array, "-"); print array[2]}' <<< ${fromTo})
                  from=$(awk '{split($0, array, "-"); print array[1]}' <<< ${fromTo})
                  repl="${line/$from-$to/$from-$year}"
              else
                  # we only have a FROM year
                  # find occurance of 4 digits
                  from=$(grep -o "[0-9]\{4\}" <<< $line || true)
                  fromTo="${from}-${year}"
                  # replace FROM with FROM-TO
                  repl=${line/"$from"/"$fromTo"}
              fi
              sed -i "s|${line}|${repl}|g" $file
          done

          # Commit the changes and push the feature branch to origin
          git add .
          git commit -m "chore: update scripts to $LATEST_TAG"
          git push origin external_bump_copyright

          # Store the PAT in a file that can be accessed by the
          # GitHub CLI.
          echo "${{ secrets.ACCESS_TOKEN }}" > token.txt

          # Authorize GitHub CLI for the current repository and
          # create a pull-requests containing the updates.
          gh auth login --with-token < token.txt
          gh pr create \
            --body "Happy new year!" \
            --title "workflows: test external pull request" \
            --head "external_bump_copyright" \
            --base "main"
