name: ci/gh-actions/gitian

on: push

jobs:
  build-gitian:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - name: "Linux"
            option: "l"
    name: ${{ matrix.operating-system.name }}
    steps:
    - name: prepare
      run: |
        sudo apt update
        curl -O https://raw.githubusercontent.com/monero-project/monero/v0.18.3.1/contrib/gitian/gitian-build.py
        chmod +x gitian-build.py
    - name: setup
      run: |
        ./gitian-build.py --setup --docker --url https://github.com/selsta/monero github-actions riscv-gitian
    - name: build
      run: |
        ./gitian-build.py --docker --detach-sign --no-commit --build -j 3 -o ${{ matrix.operating-system.option }} --url https://github.com/selsta/monero github-actions riscv-gitian
    - name: post build
      run: |
        cd out/riscv-gitian
        shasum -a256 *
        echo \`\`\` >> $GITHUB_STEP_SUMMARY
        shasum -a256 * >> $GITHUB_STEP_SUMMARY
        echo \`\`\` >> $GITHUB_STEP_SUMMARY
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.operating-system.name }}
        path: |
          out/riscv-gitian/*
